package resourcesSchemas

import (
	"service-scim/models/config"
)

var UserSchemaObject = modelsConfig.Schema{
	Id:          "urn:ietf:params:scim:schemas:core:2.0:User",
	Name:        "User",
	Description: "User Schema",
	Attributes: []*modelsConfig.Attribute{
		{
			Name:           "schemas",
			Type:           "reference",
			MultiValued:    true,
			Required:       true,
			CaseExact:      &True,
			Mutability:     "readOnly",
			Returned:       "default",
			Uniqueness:     "none",
			ReferenceTypes: []string{"uri"},
			CanonicalValues: []string{
				"urn:ietf:params:scim:schemas:core:2.0:User",
				"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
			},
			Description: "An array of Strings containing URIs that are used to indicate the namespaces of the SCIM schemas that define the attributes present in the current structure.",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Schemas",
				Path:      "schemas",
				FullPath:  "schemas",
				IndexKeys: []string{},
			},
		}, {
			Name:        "id",
			Type:        "integer",
			MultiValued: false,
			Required:    true,
			CaseExact:   &True,
			Mutability:  "readOnly",
			Returned:    "always",
			Uniqueness:  "global",
			Description: "A unique identifier for a SCIM resource as defined by the service provider.",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Id",
				Path:      "id",
				FullPath:  "id",
				IndexKeys: []string{},
			},
		}, {
			Name:        "userName",
			Type:        "string",
			MultiValued: false,
			Required:    false,
			CaseExact:   &False,
			Mutability:  "readOnly",
			Returned:    "default",
			Uniqueness:  "server",
			Description: "Unique identifier for the User, typically used by the user to directly authenticate to the service provider. Each User MUST include a non-empty userName value.  This identifier MUST be unique across the service provider's entire set of Users.",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "userName",
				Path:      "userName",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:userName",
				IndexKeys: []string{},
			},
		}, {
			Name:        "externalId",
			Type:        "string",
			MultiValued: false,
			Required:    false,
			CaseExact:   &True,
			Mutability:  "readWrite",
			Returned:    "default",
			Uniqueness:  "global",
			Description: "A String that is an identifier for the resource as defined by the provisioning client.",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "ExternalId",
				Path:      "externalId",
				FullPath:  "externalId",
				IndexKeys: []string{},
			},
		}, {
			Name:        "emails",
			Type:        "complex",
			MultiValued: true,
			Required:    true,
			Mutability:  "readWrite",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "Email addresses for the user.  The value SHOULD be canonicalized by the service provider, e.g., 'bjensen@example.com' instead of 'bjensen@EXAMPLE.COM'. Canonical type values of 'work', 'home', and 'other'.",
			SubAttributes: []*modelsConfig.Attribute{
				{
					Name:        "value",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "Email addresses for the user.  The value SHOULD be canonicalized by the service provider, e.g., 'bjensen@example.com' instead of 'bjensen@EXAMPLE.COM'. Canonical type values of 'work', 'home', and 'other'.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Value",
						Path:      "emails.value",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:emails.value",
						IndexKeys: []string{},
					},
				}, {
					Name:        "display",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readOnly",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "A human-readable name, primarily used for display purposes.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Display",
						Path:      "emails.display",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:emails.display",
						IndexKeys: []string{},
					},
				}, {
					Name:            "type",
					Type:            "string",
					MultiValued:     false,
					Required:        false,
					CaseExact:       &False,
					Mutability:      "readWrite",
					Returned:        "default",
					Uniqueness:      "none",
					CanonicalValues: []string{"work", "home", "other"},
					Description:     "A label indicating the attribute's function, e.g., 'work' or 'home'.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Type",
						Path:      "emails.type",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:emails.type",
						IndexKeys: []string{},
					},
				}, {
					Name:        "primary",
					Type:        "boolean",
					MultiValued: false,
					Required:    false,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "A Boolean value indicating the 'primary' or preferred attribute value for this attribute, e.g., the preferred mailing address or primary email address.  The primary attribute value 'true' MUST appear no more than once.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Primary",
						Path:      "emails.primary",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:emails.primary",
						IndexKeys: []string{},
					},
				},
			},
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Emails",
				Path:      "emails",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:emails",
				IndexKeys: []string{"value"},
			},
		}, {
			Name:        "name",
			Type:        "complex",
			MultiValued: false,
			Required:    false,
			Mutability:  "readWrite",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "The components of the user's real name. Providers MAY return just the full name as a single string in the formatted sub-attribute, or they MAY return just the individual component attributes using the other sub-attributes, or they MAY return both.  If both variants are returned, they SHOULD be describing the same name, with the formatted name indicating how the component attributes should be combined.",
			SubAttributes: []*modelsConfig.Attribute{
				{
					Name:        "formatted",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The full name, including all middle names, titles, and suffixes as appropriate, formatted for display (e.g., 'Ms. Barbara J Jensen, III').",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Formatted",
						Path:      "name.formatted",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:name.formatted",
						IndexKeys: []string{},
					},
				}, {
					Name:        "familyName",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The family name of the User, or last name in most Western languages (e.g., 'Jensen' given the full name 'Ms. Barbara J Jensen, III').",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "FamilyName",
						Path:      "name.familyName",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:name.familyName",
						IndexKeys: []string{},
					},
				}, {
					Name:        "givenName",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The given name of the User, or first name in most Western languages (e.g., 'Barbara' given the full name 'Ms. Barbara J Jensen, III').",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "GivenName",
						Path:      "name.givenName",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:name.givenName",
						IndexKeys: []string{},
					},
				}, {
					Name:        "middleName",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The middle name(s) of the User (e.g., 'Jane' given the full name 'Ms. Barbara J Jensen, III').",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "MiddleName",
						Path:      "name.middleName",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:name.middleName",
						IndexKeys: []string{},
					},
				}, {
					Name:        "honorificPrefix",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The honorific prefix(es) of the User, or title in most Western languages (e.g., 'Ms.' given the full name Ms. Barbara J Jensen, III').",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "HonorificPrefix",
						Path:      "name.honorificPrefix",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:name.honorificPrefix",
						IndexKeys: []string{},
					},
				}, {
					Name:        "honorificSuffix",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The honorific suffix(es) of the User, or suffix in most Western languages (e.g., 'III' given the full name 'Ms. Barbara J Jensen, III').",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "HonorificSuffix",
						Path:      "name.honorificSuffix",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:name.honorificSuffix",
						IndexKeys: []string{},
					},
				},
			},
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Name",
				Path:      "name",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:name",
				IndexKeys: []string{},
			},
		}, {
			Name:           "profileUrl",
			Type:           "reference",
			MultiValued:    false,
			Required:       false,
			CaseExact:      &False,
			Mutability:     "readOnly",
			Returned:       "default",
			Uniqueness:     "none",
			ReferenceTypes: []string{"external"},
			Description:    "A fully qualified URL pointing to a page representing the User's online profile.",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "ProfileUrl",
				Path:      "profileUrl",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:profileUrl",
				IndexKeys: []string{},
			},
		}, {
			Name:        "title",
			Type:        "string",
			MultiValued: false,
			Required:    false,
			CaseExact:   &False,
			Mutability:  "readWrite",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "The user's job title, such as 'Vice President.'",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Title",
				Path:      "title",
				FullPath:  "title",
				IndexKeys: []string{},
			},
		}, {
			Name:        "locale",
			Type:        "string",
			MultiValued: false,
			Required:    false,
			CaseExact:   &False,
			Mutability:  "readOnly",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "Used to indicate the User's default location for purposes of localizing items such as currency, date time format, or numerical representations.",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Locale",
				Path:      "locale",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:locale",
				IndexKeys: []string{},
			},
		}, {
			Name:        "timezone",
			Type:        "string",
			MultiValued: false,
			Required:    false,
			CaseExact:   &False,
			Mutability:  "readWrite",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "The User's time zone in the 'Olson' time zone database format, e.g., 'America/Los_Angeles'.",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Timezone",
				Path:      "timezone",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:timezone",
				IndexKeys: []string{},
			},
		}, {
			Name:        "active",
			Type:        "boolean",
			MultiValued: false,
			Required:    false,
			Mutability:  "readWrite",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "A Boolean value indicating the User's administrative status.",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Active",
				Path:      "active",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:active",
				IndexKeys: []string{},
			},
		}, {
			Name:        "password",
			Type:        "string",
			MultiValued: false,
			Required:    false,
			CaseExact:   &False,
			Mutability:  "writeOnly",
			Returned:    "never",
			Uniqueness:  "none",
			Description: "The User's cleartext password. This attribute is intended to be used as a means to specify an initial password when creating a new User or to reset an existing User's password.",
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Password",
				Path:      "password",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:password",
				IndexKeys: []string{},
			},
		}, {
			Name:        "phoneNumbers",
			Type:        "complex",
			MultiValued: true,
			Required:    false,
			Mutability:  "readWrite",
			Returned:    "default",
			Description: "Phone numbers for the User. The value SHOULD be canonicalized by the service provider according to the format specified in RFC 3966, e.g., 'tel:+1-201-555-0123'. Canonical type values of 'work', 'home', 'mobile', 'fax', 'pager', and 'other'.",
			SubAttributes: []*modelsConfig.Attribute{
				{
					Name:        "value",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "Phone number of the User.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Value",
						Path:      "phoneNumbers.value",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers.value",
						IndexKeys: []string{},
					},
				}, {
					Name:        "display",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readOnly",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "A human-readable name, primarily used for display purposes.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Display",
						Path:      "phoneNumbers.display",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers.display",
						IndexKeys: []string{},
					},
				}, {
					Name:            "type",
					Type:            "string",
					MultiValued:     false,
					Required:        false,
					CaseExact:       &False,
					Mutability:      "readWrite",
					Returned:        "default",
					Uniqueness:      "none",
					CanonicalValues: []string{"work", "home", "mobile", "fax", "other"},
					Description:     "A label indicating the attribute's function, e.g., 'work', 'home', 'mobile'.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Type",
						Path:      "phoneNumbers.type",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers.type",
						IndexKeys: []string{},
					},
				}, {
					Name:        "primary",
					Type:        "boolean",
					MultiValued: false,
					Required:    false,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "A Boolean value indicating the 'primary' or preferred attribute value for this attribute, e.g., the preferred phone number or primary phone number.  The primary attribute value 'true' MUST appear no more than once.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Primary",
						Path:      "phoneNumbers.primary",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers.primary",
						IndexKeys: []string{},
					},
				},
			},
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "PhoneNumbers",
				Path:      "phoneNumbers",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers",
				IndexKeys: []string{"value"},
			},
		}, {
			Name:        "photos",
			Type:        "complex",
			MultiValued: true,
			Required:    false,
			Mutability:  "readOnly",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "URLs of photos of the User.",
			SubAttributes: []*modelsConfig.Attribute{
				{
					Name:           "value",
					Type:           "reference",
					MultiValued:    false,
					Required:       false,
					CaseExact:      &False,
					Mutability:     "readOnly",
					Returned:       "default",
					Uniqueness:     "none",
					ReferenceTypes: []string{"external"},
					Description:    "URL of a photo of the User.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Value",
						Path:      "photos.value",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:photos.value",
						IndexKeys: []string{},
					},
				}, {
					Name:            "type",
					Type:            "string",
					MultiValued:     false,
					Required:        false,
					CaseExact:       &False,
					Mutability:      "readOnly",
					Returned:        "default",
					Uniqueness:      "none",
					CanonicalValues: []string{"photo", "thumbnail"},
					Description:     "A label indicating the attribute's function, i.e., 'photo' or 'thumbnail'.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Type",
						Path:      "photos.type",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:photos.type",
						IndexKeys: []string{},
					},
				},
			},
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Photos",
				Path:      "photos",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:photos",
				IndexKeys: []string{"value"},
			},
		}, {
			Name:        "addresses",
			Type:        "complex",
			MultiValued: true,
			Required:    false,
			Mutability:  "readWrite",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "A physical mailing address for this User.  Canonical type values of 'work', 'home', and 'other'.  This attribute is a complex type with the following sub-attributes.",
			SubAttributes: []*modelsConfig.Attribute{
				{
					Name:        "streetAddress",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The full street address component, which may include house number, street name, P.O. box, and multi-line extended street address information. This attribute MAY contain newlines.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "StreetAddress",
						Path:      "addresses.streetAddress",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:addresses.streetAddress",
						IndexKeys: []string{},
					},
				}, {
					Name:        "locality",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The city or locality component.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Locality",
						Path:      "addresses.locality",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:addresses.locality",
						IndexKeys: []string{},
					},
				}, {
					Name:        "region",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The state or region component.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Region",
						Path:      "addresses.region",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:addresses.region",
						IndexKeys: []string{},
					},
				}, {
					Name:        "postalCode",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The zip code or postal code component.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "PostalCode",
						Path:      "addresses.postalCode",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:addresses.postalCode",
						IndexKeys: []string{},
					},
				}, {
					Name:        "country",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The country name component.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Country",
						Path:      "addresses.country",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:addresses.country",
						IndexKeys: []string{},
					},
				}, {
					Name:            "type",
					Type:            "string",
					MultiValued:     false,
					Required:        false,
					CaseExact:       &False,
					Mutability:      "readWrite",
					Returned:        "default",
					Uniqueness:      "none",
					CanonicalValues: []string{"work", "home", "other"},
					Description:     "A label indicating the attribute's function, e.g., 'work' or 'home'.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Type",
						Path:      "addresses.type",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:addresses.type",
						IndexKeys: []string{},
					},
				}, {
					Name:        "primary",
					Type:        "boolean",
					MultiValued: false,
					Required:    false,
					Mutability:  "readWrite",
					Returned:    "default",
					Description: "A Boolean value indicating the 'primary' or preferred attribute value for this attribute, e.g., the preferred messenger or primary messenger.  The primary attribute value 'true' MUST appear no more than once.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Primary",
						Path:      "addresses.primary",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:addresses.primary",
						IndexKeys: []string{},
					},
				},
			},
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Addresses",
				Path:      "addresses",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:addresses",
				IndexKeys: []string{"streetAddress", "locality", "region", "postalCode", "country"},
			},
		}, {
			Name:        "groups",
			Type:        "complex",
			MultiValued: true,
			Required:    false,
			Mutability:  "readOnly",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "A list of groups to which the user belongs.",
			SubAttributes: []*modelsConfig.Attribute{
				{
					Name:        "value",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readOnly",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The identifier of the User's group.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Value",
						Path:      "groups.value",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:groups.value",
						IndexKeys: []string{},
					},
				}, {
					Name:           "$ref",
					Type:           "reference",
					MultiValued:    false,
					Required:       false,
					CaseExact:      &False,
					Mutability:     "readOnly",
					Returned:       "default",
					Uniqueness:     "none",
					ReferenceTypes: []string{"Group"},
					Description:    "The URI of the corresponding 'Group' resource to which the user belongs.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Ref",
						Path:      "groups.$ref",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:groups.$ref",
						IndexKeys: []string{},
					},
				}, {
					Name:        "display",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readOnly",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "A human-readable name, primarily used for display purposes.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Display",
						Path:      "groups.display",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:groups.display",
						IndexKeys: []string{},
					},
				},
			},
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Groups",
				Path:      "groups",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:groups",
				IndexKeys: []string{"value"},
			},
		}, {
			Name:        "roles",
			Type:        "complex",
			MultiValued: true,
			Required:    false,
			Mutability:  "readWrite",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "A list of roles for the User that collectively represent who the User is, e.g., 'Manager', 'Operator'.",
			SubAttributes: []*modelsConfig.Attribute{
				{
					Name:        "value",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readWrite",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The value of a role.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Value",
						Path:      "roles.value",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:roles.value",
						IndexKeys: []string{},
					},
				}, {
					Name:        "display",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &False,
					Mutability:  "readOnly",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "A human-readable name, primarily used for display purposes.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Display",
						Path:      "roles.display",
						FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:roles.display",
						IndexKeys: []string{},
					},
				},
			},
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Roles",
				Path:      "roles",
				FullPath:  "urn:ietf:params:scim:schemas:core:2.0:User:roles",
				IndexKeys: []string{"value"},
			},
		}, {
			Name:        "meta",
			Type:        "complex",
			MultiValued: false,
			Required:    false,
			Mutability:  "readOnly",
			Returned:    "default",
			Uniqueness:  "none",
			Description: "Resource metadata.",
			SubAttributes: []*modelsConfig.Attribute{
				{
					Name:        "resourceType",
					Type:        "string",
					MultiValued: false,
					Required:    false,
					CaseExact:   &True,
					Mutability:  "readOnly",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The name of the resource type of the resource.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "ResourceType",
						Path:      "meta.resourceType",
						FullPath:  "meta.resourceType",
						IndexKeys: []string{},
					},
				}, {
					Name:           "location",
					Type:           "reference",
					MultiValued:    false,
					Required:       false,
					CaseExact:      &True,
					Mutability:     "readOnly",
					Returned:       "default",
					Uniqueness:     "none",
					ReferenceTypes: []string{"uri"},
					Description:    "The URI of the resource being returned.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Location",
						Path:      "meta.location",
						FullPath:  "meta.location",
						IndexKeys: []string{},
					},
				}, {
					Name:        "created",
					Type:        "datetime",
					MultiValued: false,
					Required:    false,
					CaseExact:   &True,
					Mutability:  "readOnly",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The 'DateTime' that the resource was added to the service provider.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "Created",
						Path:      "meta.created",
						FullPath:  "meta.created",
						IndexKeys: []string{},
					},
				}, {
					Name:        "lastModified",
					Type:        "datetime",
					MultiValued: false,
					Required:    false,
					CaseExact:   &True,
					Mutability:  "readOnly",
					Returned:    "default",
					Uniqueness:  "none",
					Description: "The 'DateTime' that the resource was updated last time.",
					Navigation: &modelsConfig.AttributeNavigation{
						FieldName: "LastModified",
						Path:      "meta.lastModified",
						FullPath:  "meta.lastModified",
						IndexKeys: []string{},
					},
				},
			},
			Navigation: &modelsConfig.AttributeNavigation{
				FieldName: "Meta",
				Path:      "meta",
				FullPath:  "meta",
				IndexKeys: []string{},
			},
		},
		EnterpriseExtensionAttribute,
	},
	Meta: &modelsConfig.SchemaMeta{
		Location:     "/Schemas/urn:ietf:params:scim:schemas:core:2.0:User",
		ResourceType: "Schema",
	},
}
