[[constraint]]
  name = "gitlab.com/***/lib-go-logger"
  source = "git@gitlab.com:***/lib-go-logger.git"
  version = "~0.3.2"

[[constraint]]
  name = "gitlab.com/***/lib-beego-logger"
  source = "git@gitlab.com:***/lib-beego-logger.git"
  version = "~0.1"

[[constraint]]
  name = "gitlab.com/***/sdk-go-configurator"
  source = "git@gitlab.com:***/sdk-go-configurator.git"
  version = "~0.4.14"

[[constraint]]
  name = "github.com/astaxie/beego"
  version = "~1.11"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.2"

[prune]
  go-tests = true
  unused-packages = true
